#pragma once

// √¸¡Ó√∂æŸ
enum EntryCmdList { DISABLEKEYBOARD, DISABLEMOUSE, ENABLENOTIFYICON, CONFIRMONQUIT, IGNOREWHEEL, DISCARDWIN,
	SHOWLIFEBAR, SHOWENEMYBAR, SHOWALLYBAR, ENABLEWINDOWFUNC, SKIPWINDOWMODEDETECT, ENABLECLIPCURSOR, ENABLELOCKRATIO, ENABLEAUXFUNC, ENABLEINPUTCHECK, ENABLEINPUTCHECK122, ENABLEINPUTCHECK123, ENABLEINPUTCHECK124, ENABLERESTRICT, RESTRICTMINIMAPRCLICK, RESTRICTMINIMAPBUTTONS,
	ALLTOGGLE, TEMPAUXKEY, 
	ITEMTOGGLE, ITEM0, ITEM1, ITEM2, ITEM3, ITEM4, ITEM5,
	MOUSETOGGLE, SELPORTRAITKEY, CONTINUOUSCLICK, AUTOCASTKEY, 
	MOUSESKILL1, MOUSESKILL2, MOUSESKILL3, MOUSESKILL4, MOUSESKILL5, MOUSESKILL6, MOUSESKILL7, 
	REPLAYPAUSE, REPLAYSPEEDUP, REPLAYSLOWDOWN, REPLAYRELOAD,
	KAELTOGGLE, KAELVERSION, KAELCAST, KAEL0, KAEL1, KAEL2, KAEL3, KAEL4, KAEL5, KAEL6, KAEL7, KAEL8, KAEL9, 
	CHATTOGGLE, CHAT0, CHAT1, CHAT2, CHAT3, CHAT4, CHAT5, CHAT6, CHAT7, CHAT8, CHAT9,
	CHATTARGET0, CHATTARGET1, CHATTARGET2, CHATTARGET3, CHATTARGET4, CHATTARGET5, CHATTARGET6, CHATTARGET7, CHATTARGET8, CHATTARGET9};
